markers:
  0: "small_box_marker_0"
  1: "small_box_marker_1"
  2: "small_box_marker_2"
  3: "small_box_marker_3"
  4: "small_box_marker_4"
  5: "small_box_marker_5"
  6: "small_box_marker_6"
  7: "small_box_marker_7"
  8: "small_box_marker_8"
  9: "small_box_marker_9"
